# Generated by Django 6.1.1 on 2026-09-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional & Formal'), ('friendly', 'Friendly & Warm'), ('persuasive', 'Persuasive & Sales'), ('concise', 'Direct & Concise'), ('casual', 'Casual & Conversational')], default='professional', max_length=50),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='description',
            field=models.TextField(help_text='Core instructions for the email'),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='generated_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='receiver_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
